const sweDict = {"Luscinia svecica": "blåhake",
"Acanthis flammea": "gråsiska",
"Accipiter gentilis": "duvhök",
"Accipiter nisus": "sparvhök",
"Acrocephalus arundinaceus": "trastsångare",
"Actitis hypoleucos": "drillsnäppa",
"Aegithalos caudatus": "stjärtmes",
"Alauda arvensis": "sånglärka",
"Alca torda": "tordmule",
"Alcedo atthis": "kungsfiskare",
"Anas crecca": "kricka",
"Anas platyrhynchos": "gräsand",
"Anser anser": "grågås",
"Anser fabalis": "sädgås",
"Anthus pratensis": "ängspiplärka",
"Aquila chrysaetos": "kungsörn",
"Ardea alba": "ägretthäger",
"Ardea cinerea": "gråhäger",
"Aythya ferina": "brunand",
"Aythya fuligula": "vigg",
"Bombycilla garrulus": "sidensvans",
"Botaurus stellaris": "rördrom",
"Branta canadensis": "kanadagås",
"Bucephala clangula": "knipa",
"Buteo buteo": "ormvråk",
"Buteo lagopus": "fjällvråk",
"Calidris pugnax": "brushane",
"Carduelis carduelis": "steglits",
"Certhia familiaris": "trädkrypare",
"Charadrius dubius": "mindre strandpipare",
"Charadrius hiaticula": "större strandpipare",
"Charadrius morinellus": "fjällpipare",
"Chloris chloris": "grönfink",
"Chroicocephalus ridibundus": "skrattmås",
"Cinclus cinclus": "strömstare",
"Circus aeruginosus": "brun kärrhök",
"Coccothraustes coccothraustes": "stenknäck",
"Columba livia forma domestica": "tamduva",
"Columba oenas": "skogsduva",
"Columba palumbus": "ringduva",
"Corvus corone": "kråka",
"Corvus frugilegus": "råka",
"Corvus monedula": "kaja",
"Coturnix coturnix": "vaktel",
"Cuculus canorus": "gök",
"Curruca communis": "törnsångare",
"Curruca curruca": "ärtsångare",
"Cyanistes caeruleus": "blåmes",
"Cygnus cygnus": "sångsvan",
"Cygnus olor": "knölsvan",
"Delichon urbicum": "hussvala",
"Dendrocopos major": "större hackspett",
"Dryobates minor": "mindre hackspett",
"Dryocopus martius": "spillkråka",
"Emberiza citrinella": "gulsparv",
"Emberiza hortulana": "ortolansparv",
"Emberiza schoeniclus": "sävsparv",
"Erithacus rubecula": "rödhake",
"Falco peregrinus": "pilgrimsfalk",
"Falco subbuteo": "lärkfalk",
"Falco tinnunculus": "tornfalk",
"Ficedula albicollis": "halsbandsflugsnappare",
"Ficedula hypoleuca": "svartvit flugsnappare",
"Fringilla coelebs": "bofink",
"Fringilla montifringilla": "bergfink",
"Fulica atra": "sothöna",
"Gallinago gallinago": "enkelbeckasin",
"Gallinago media": "dubbelbeckasin",
"Gallinula chloropus": "rörhöna",
"Garrulus glandarius": "nötskrika",
"Gavia adamsii": "vitnäbbad islom",
"Gavia arctica": "storlom",
"Gavia stellata": "smålom",
"Grus grus": "trana",
"Haematopus ostralegus": "strandskata",
"Haliaeetus albicilla": "havsörn",
"Hippolais icterina": "härmsångare",
"Hirundo rustica": "ladusvala",
"Hydrocoloeus minutus": "dvärgmås",
"Hydroprogne caspia": "skräntärna",
"Jynx torquilla": "göktyta",
"Lagopus lagopus": "dalripa",
"Lagopus muta": "fjällripa",
"Lanius collurio": "törnskata",
"Lanius excubitor": "varfågel",
"Larus argentatus": "gråtrut",
"Larus canus": "fiskmås",
"Larus fuscus": "silltrut",
"Larus marinus": "havstrut",
"Limosa lapponica": "myrspov",
"Limosa limosa": "rödspov",
"Linaria cannabina": "hämpling",
"Linaria flavirostris": "vinterhämpling",
"Locustella fluviatilis": "flodsångare",
"Locustella luscinioides": "vassångare",
"Locustella naevia": "gräshoppsångare",
"Lophophanes cristatus": "tofsmes",
"Loxia pytyopsittacus": "större korsnäbb",
"Lullula arborea": "trädlärka",
"Luscinia luscinia": "näktergal",
"Luscinia megarhynchos": "sydnäktergal",
"Luscinia svecica": "blåhake",
"Lymnocryptes minimus": "dvärgbeckasin",
"Mareca penelope": "bläsand",
"Mareca strepera": "snatterand",
"Melanitta fusca": "svärta",
"Melanitta nigra": "sjöorre",
"Mergellus albellus": "salskrake",
"Mergus merganser": "storskrake",
"Mergus serrator": "småskrake",
"Milvus milvus": "röd glada",
"Motacilla alba": "sädesärla",
"Motacilla cinerea": "forsärla",
"Motacilla flava": "gulärla",
"Muscicapa striata": "grå flugsnappare",
"Numenius arquata": "storspov",
"Numenius phaeopus": "småspov",
"Oenanthe oenanthe": "stenskvätta",
"Pandion haliaetus": "fiskgjuse",
"Panurus biarmicus": "skäggmes",
"Parus major": "talgoxe",
"Passer montanus": "pilfink",
"Pernis apivorus": "bivråk",
"Phalacrocorax carbo": "storskarv",
"Phalaropus lobatus": "smalnäbbad simsnäppa",
"Phasianus colchicus": "fasan",
"Phoenicurus phoenicurus": "rödstjärt",
"Phylloscopus collybita": "gransångare",
"Phylloscopus sibilatrix": "grönsångare",
"Phylloscopus trochilus": "lövsångare",
"Pica pica": "skata",
"Picus canus": "gråspett",
"Picus viridis": "gröngöling",
"Pinicola enucleator": "tallbit",
"Pluvialis apricaria": "ljungpipare",
"Podiceps auritus": "svarthakedopping",
"Podiceps cristatus": "skäggdopping",
"Podiceps grisegena": "gråhakedopping",
"Poecile montanus": "talltita",
"Poecile palustris": "entita",
"Prunella modularis": "järnsparv",
"Pyrrhula pyrrhula": "domherre",
"Rallus aquaticus": "vattenrall",
"Recurvirostra avosetta": "skärfläcka",
"Regulus ignicapilla": "brandkronad kungsfågel",
"Regulus regulus": "kungsfågel",
"Saxicola rubetra": "buskskvätta",
"Scolopax rusticola": "morkulla",
"Sitta europaea": "nötväcka",
"Somateria mollissima": "ejder",
"Spatula clypeata": "skedand",
"Spatula querquedula": "årta",
"Spinus spinus": "grönsiska",
"Stercorarius longicaudus": "fjällabb",
"Sterna hirundo": "fisktärna",
"Sterna paradisaea": "silvertärna",
"Streptopelia decaocto": "turkduva",
"Strix aluco": "kattuggla",
"Strix nebulosa": "lappuggla",
"Sturnus vulgaris": "stare",
"Surnia ulula": "hökuggla",
"Sylvia atricapilla": "svarthätta",
"Sylvia borin": "trädgårdssångare",
"Tachybaptus ruficollis": "smådopping",
"Tadorna tadorna": "gravand",
"Tetrastes bonasia": "järpe",
"Tringa erythropus": "svartsnäppa",
"Tringa glareola": "grönbena",
"Tringa nebularia": "gluttsnäppa",
"Tringa ochropus": "skogssnäppa",
"Tringa totanus": "rödbena",
"Troglodytes troglodytes": "gärdsmyg",
"Turdus iliacus": "rödvingetrast",
"Turdus merula": "koltrast",
"Turdus pilaris": "björktrast",
"Turdus viscivorus": "dubbeltrast",
"Vanellus vanellus": "tofsvipa",
"Bubo bubo": "berguv",
"Carpodacus erythrinus": "rosenfink",
"Strix uralensis": "slaguggla ",
"Lyrurus tetrix": "orre",
"Acrocephalus scirpaceus": "rörsångare",
"Periparus ater": "svartmes",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": ""}