const categories = {"Warblers": [
"Acrocephalus arundinaceus",
"Acrocephalus scirpaceus",
"Curruca communis",
"Curruca curruca",
"Hippolais icterina",
"Locustella fluviatilis",
"Locustella luscinioides",
"Locustella naevia",
"Phylloscopus collybita",
"Phylloscopus sibilatrix",
"Phylloscopus trochilus",
"Sylvia borin",
"Acrocephalus schoenobaenus",
"Acrocephalus palustris",
"Sylvia atricapilla",
"",
"",
"",
"",
],

"Thrushes": [
"Turdus iliacus",
"Turdus merula",
"Turdus pilaris",
"Turdus viscivorus",
"Turdus philomelos",
"",
"",
"",
"",
],

"Waders": [
"Actitis hypoleucos",
"Phalaropus lobatus",
"Tringa erythropus",
"Tringa glareola",
"Tringa nebularia",
"Tringa ochropus",
"Tringa totanus",
"Limosa lapponica",
"Limosa limosa",
"Numenius arquata",
"Numenius phaeopus",
"Calidris pugnax",
"Recurvirostra avosetta",
"Scolopax rusticola",
"Gallinago gallinago",
"Gallinago media",
"Pluvialis apricaria",
"Charadrius dubius",
"Charadrius hiaticula",
"Charadrius morinellus",
"",
"",
"",
"",
],

"Owls": [
"Strix aluco",
"Strix nebulosa",
"Surnia ulula",
"Strix uralensis",
"Bubo bubo",
"Aegolius funereus",
"Glaucidium passerinum",
"Asio flammeus",
"Asio otus",
"Tyto alba"
],

"Woodpeckers": [
"Dendrocopos major",
"Dryobates minor",
"Dryocopus martius",
"Picus viridis",
"Picus canus",
"Dendrocopos leucotos",
"Picoides tridactylus",
"",
"",
"",
"",
"", 
],

"Flycatcher": [
"Luscinia svecica",
"Erithacus rubecula",
"Oenanthe oenanthe",
"Saxicola rubetra",
"Ficedula albicollis",
"Ficedula hypoleuca",
"Muscicapa striata",
"Ficedula parva",
"Phoenicurus phoenicurus",
"",
"",
"",
"",
"",
"", 
],
"Finches": [
"Fringilla coelebs",
"Fringilla montifringilla",
"Carpodacus erythrinus",
"Chloris chloris",
"", 
"",
"",
"",
"",
"", 
"",
"",
"",
"",
"", 
],
"Tits": [
"Lophophanes cristatus",
"Periparus ater", 
"Cyanistes caeruleus",
"Poecile montanus",
"Poecile palustris",
"Parus major",
"", 
"",
"",
"",
"",
"", 
]};